Controllers/PostController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Distro2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Distro2.Areas.Identity.Data;
using Distro2.DAL;

namespace Distro2.Controllers
{
    //Controller for the posting page
    [Authorize]
    public class PostController : Controller
    {
        private readonly UserManager<Distro2User> _userManager;
        private readonly IUserRepository _userRepository;
        private readonly IMessageRepository _messageRepository;


        public PostController(UserManager<Distro2User> userManager)
        {
            _userRepository = new UserRepository();
            _messageRepository = new MessageRepository();
            _userManager = userManager;
        }

        // GET
        // Gets information necessary for posting template and updates view. 
        public async Task<IActionResult> Index(string? id)
        {
            var users = await _userRepository.GetUsers();
            ViewData["Users"] = (users);
            var postmess = new PostMessageModel();
            postmess.users = new SelectList(users);
            if (id != "" && id != null)
                ViewBag.Confirm = id;
            else
                ViewBag.Confirm = null;
            return View(postmess);
        }



        // POST
        // Creates a post and updates the database. Updates view to confirm a message is sent. 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Title, Body, user")] PostMessageModel Postmess)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (await _messageRepository.PostMessage(Postmess, _userManager.GetUserName(HttpContext.User)))
                    {
                        return RedirectToAction("Index", new { id = Postmess.user });
                    }
                }
                catch (Exception e) { }
            }
            return RedirectToAction("Index", new { id = "" });
        }
    }
}

Controllers/ReadController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Distro2.DAL;
using Microsoft.AspNetCore.Authorization;
using System;

namespace Distro2.Controllers
{
    //Controller for reading received messages
    [Authorize]
    public class ReadController : Controller
    {
        private readonly IMessageRepository _messageRepository;
        private readonly IUserRepository _userRepository;

        public ReadController()
        {
            _messageRepository = new MessageRepository();
            _userRepository = new UserRepository();
        }

        //Read/Index
        // Updates view with users who have sent the user messages, aswell as displaying total messages, read messages and deleted messages. 
        public async Task<IActionResult> Index()
        {
            var id = User.Identity.Name;
            int totMessages = await _messageRepository.NumberOfTotalMessages(id);
            int unreadMessages = await _messageRepository.NumberOfUnreadMessages(id);
            ViewBag.totalMessages = totMessages;
            ViewBag.ReadMessages = totMessages - unreadMessages;
            ViewBag.NrOfDeletions = _userRepository.NrOfDeletions(id).Result;
            return View(await _messageRepository.getReceivedUsers(await _userRepository.GetUsers(), id));
        }

        // GET: Read/Inbox
        //Shows messages from sender with corresponding id
        public async Task<IActionResult> Inbox(string? id)
        {

            return View(await _messageRepository.GetMessagesForUser(id));
        }


        // GET: Read/Details/id
        //Details about a message with a id. 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            if (!CorrectUser(id))
            {
                return NotFound();
            }

            var message = await _messageRepository.GetDetails(id);
            ViewData["SendUser"] = message.Sender;

            if (message == null)
               return NotFound();

            return View(message);
        }


        // GET: Read/Delete/id
        //display delete template for a message with a certain id. 
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            if (!CorrectUser(id))
            {
                return NotFound();
            }

            var message = await _messageRepository.GetDetails(id);
            ViewData["SendUser"] = message.Sender;

            if (message == null)
                return NotFound();

            return View(message);
        }

        // POST: Post/Delete/id
        //Delete a message from the database with a certain id. 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _messageRepository.DeleteMessage(id);
            _userRepository.updateDeletions(user);
            return RedirectToAction("Inbox", new { id = user });
        }


        private Boolean CorrectUser(int? id)
        {
            if (_messageRepository.GetDetails(id).Result.Receiver == User.Identity.Name)
                return true;
            return false;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MSN 2.0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MSN 2.0</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Read" asp-action="Index">Read</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MSN 2.0
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>